# Generated by Django 4.1.2 on 2022-11-08 22:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DjangoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=150,
                 unique=True, verbose_name='type name')),
            ],
            options={
                'verbose_name': 'django model',
                'verbose_name_plural': 'django models',
                'db_table': 'django_data_battery_django_models',
            },
        ),
        migrations.CreateModel(
            name='UpdatedIds',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('django_model', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='django_data_battery.djangomodel')),
            ],
            options={
                'verbose_name': 'updated id',
                'verbose_name_plural': 'updated ids',
                'db_table': 'django_data_battery_updated_ids',
            },
        ),
        migrations.CreateModel(
            name='InsertedIds',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('django_model', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='django_data_battery.djangomodel')),
            ],
            options={
                'verbose_name': 'inserted id',
                'verbose_name_plural': 'inserted ids',
                'db_table': 'django_data_battery_inserted_ids',
            },
        ),
        migrations.CreateModel(
            name='InflightUpdateIds',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('django_model', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='django_data_battery.djangomodel')),
            ],
            options={
                'verbose_name': 'inflight update id',
                'verbose_name_plural': 'inflight update ids',
                'db_table': 'django_data_battery_inflight_update_ids',
            },
        ),
        migrations.CreateModel(
            name='InflightInsertIds',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('django_model', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='django_data_battery.djangomodel')),
            ],
            options={
                'verbose_name': 'inflight insert id',
                'verbose_name_plural': 'inflight insert ids',
                'db_table': 'django_data_battery_inflight_insert_ids',
            },
        ),
        migrations.CreateModel(
            name='InflightDeleteIds',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('django_model', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='django_data_battery.djangomodel')),
            ],
            options={
                'verbose_name': 'inflight delete id',
                'verbose_name_plural': 'inflight delete ids',
                'db_table': 'django_data_battery_inflight_delete_ids',
            },
        ),
        migrations.CreateModel(
            name='DeletedIds',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('django_model', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='django_data_battery.djangomodel')),
            ],
            options={
                'verbose_name': 'deleted id',
                'verbose_name_plural': 'deleted ids',
                'db_table': 'django_data_battery_deleted_ids',
            },
        ),
        migrations.CreateModel(
            name='DatabaseConnectionSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('engine', models.CharField(
                    max_length=150, verbose_name='database engine')),
                ('name', models.CharField(max_length=150, verbose_name='database name')),
                ('user', models.CharField(max_length=150, verbose_name='database user')),
                ('password', models.CharField(
                    max_length=150, verbose_name='database password')),
                ('host', models.CharField(max_length=150, verbose_name='database host')),
                ('port', models.CharField(max_length=150, verbose_name='database port')),
            ],
            options={
                'verbose_name': 'database connection settings',
                'verbose_name_plural': 'databases connections settings',
                'db_table': 'django_data_battery_database_connection_settings',
            },
        ),
    ]
